force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarIntegration.cls
@RestResource(urlMapping='/Cars/*')
global with sharing class CarIntegration {

  @HttpPost
  global static void createCar(String jsonBody) {
    // Deserializa o JSON
    Map<String, Object> carJson = (Map<String, Object>) JSON.deserializeUntyped(jsonBody);

    // Cria um novo objeto Carro
    Car__c newCar = new Car__c();
    newCar.Name = (String) carJson.get('name');
    newCar.Price__c = (Double) carJson.get('price');
    newCar.Brand__c = (String) carJson.get('brand');

    // Insere o registro no objeto Carro
    insert newCar;
  }
}